### ISSUE TITLE
[Documentation] Link to ros packages

### ISSUE THREAD

**Issue by ezvk7740** [araffin/robotics-rl-srl#35]
Hi, I am working to implement this S-RL toolbox on the Baxter Robot. I will be opening my repo to public in the upcoming weeks (everything is a mess, since I am not a programmer). I will be sure to credit you.

In the documentation, to start ros nodes on python2

roslaunch arm_scenario_simulator baxter_world.launch
rosrun arm_scenario_simulator spawn_objects_example

however, arm_scenario_simulator is missing as part of ros environment package
I looked it up and it is a gazebo environment based on ros indigo, which is not what this repo uses which is ros kinetic. 
Where can I obtain the ROS Kinetic version of this? 
Can I request the package you have used when you are writing the documentation?

I am using 
Docker
Ubuntu Xenial:arm64v8
python2.7
dependency pip installed + from source
tensorflow=1.9.0
Cuda=9.0

**Comment by araffin** [comment]
Hello,

> I looked it up and it is a gazebo environment based on ros indigo, which is not what this repo uses which is ros kinetic.

We also used kinetic.

Apparently, we forgot to link to the correct repos (I will update the documentation):
- [arm scenario experiments](https://github.com/NataliaDiaz/arm_scenario_experiments/tree/rl), branch "rl"
- [arm scenario simulator](https://github.com/araffin/arm_scenario_simulator) branch kinetic-devel

>In the documentation, to start ros nodes on python2

Also, be aware that the rest of the code requires python >= 3.5 because of stable baselines.

**Comment by ezvk7740** [comment]
Thanks for the speedy reply!
I got the gazebo model working but encountered another issue when starting ros nodes:

python -m real_robots.gazebo_server
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/robotics-rl-srl/real_robots/gazebo_server.py", line 80, in <module>
    possible_actions = getActions(DELTA_POS, n_actions=6)
  File "real_robots/utils.py", line 58, in getActions
    assert len(actions) == n_actions, "Wrong number of actions: {}".format(len(actions))
AssertionError: Wrong number of actions: 0

I am rather confused here as the number of actions set is not zero, but the error indicates that it is zero.

**Comment by araffin** [comment]
Did you change the appropriate constants in https://github.com/araffin/robotics-rl-srl/blob/master/real_robots/constants.py ? 

cf "working with a real baxter" in the [documentation](https://s-rl-toolbox.readthedocs.io/en/latest/guide/real_robots.html)

I suspect that you kept USING_ROBOBO to True (https://github.com/araffin/robotics-rl-srl/blob/master/real_robots/constants.py#L11)

**Comment by ezvk7740** [comment]
Sorry, I did not know that keeping robobo constant set as true would affect simulation in gazebo. 
Thanks, I finally got it working now. I can now get to work for real now.

**Comment by araffin** [comment]
Cool, then closing the issue ;)
