### ISSUE TITLE
How to load environment in the gym

### ISSUE THREAD

**Issue by sxwgit** [araffin/robotics-rl-srl#39]
Hello,I am very grateful to you for providing an excellent toolbox for everyone.
You use the method of class inheritance to create the environment, but there is a small problem, this method is not convenient to call the environment directly,just like
`env=gym.make('kuka')`
Would you mind tell me how to load the environment in the gym?
Best regards. Thank you.

**Comment by araffin** [comment]
Hello,

What you are looking for is registering the env with gym (see [here](https://github.com/openai/gym/wiki/Environments)).
In fact, it is already done [here](https://github.com/araffin/robotics-rl-srl/blob/master/environments/registry.py#L66).

So, doing something like:

```python
import gym

import environments.registry

env = gym.make("KukaButtonGymEnv-v0")
```
should work.

You have even a simpler solution:

```python
from environments.kuka_button_gym_env import KukaButtonGymEnv

env = KukaButtonGymEnv()
```

But normally, you don't need that, as all the scripts you need are normally already there in the toolbox.

**Comment by sxwgit** [comment]
Thank you very much for your reply, I will try it as soon as possible( if it works ,i will close this issue).
I saw that you submitted a merge about gail( #206), hope it will fix the bug(because i'm working on it. lol).
The development of rl is inseparable from your efforts, thank you for your work.

**Comment by sxwgit** [comment]
Hello , I can load the environment using 
```
import gym

import environments.registry

env = gym.make("KukaButtonGymEnv-v0")
```
But when i want to use `render()` , it didnt appear anything and return `array([], dtype=float64)`.

I want to fix it in `kuka_button_gym_env.py` : the mode parameter in render() is defaulted to 'human',so it will return  np.array([])

I set the mode equal to "rgb_array", and it return a  new reset?

In the gym environment, an image should be displayed using the render().

Would you mind tell me its a future or a bug in this toolbox?

Thank you !

**Comment by araffin** [comment]
Hello, this is normal and due to the way pybullet works. You'll need to pass renders=True to the constructor. (Please look at the code for more details)

**Comment by sxwgit** [comment]
Oh, sorry.
Thank you very much for your reply
