### ISSUE TITLE
[Question (unsolved)] Why use different preprocessImage mode in SRL/RL (convert_to_rgb=True/False)?

### ISSUE THREAD

**Issue by ncble** [araffin/robotics-rl-srl#55]
### Describe the bug
During the SRL training, you use the DataLoader
In the definition of the function `preprocessImage` you set `convert_to_rgb=True` as default value.
- https://github.com/araffin/srl-zoo/blob/438a05ab625a2c5ada573b47f73469d92de82132/preprocessing/data_loader.py#L38

In the `DataLoader`, you use the default value for `convert_to_rgb` (which is `True`)
- https://github.com/araffin/srl-zoo/blob/438a05ab625a2c5ada573b47f73469d92de82132/preprocessing/data_loader.py#L251

However, during the RL training, you use `convert_to_rgb=False`...
- https://github.com/araffin/robotics-rl-srl/blob/1ab1bd366825f98f0282d05e32a3de0cbf7f0f9a/state_representation/models.py#L178-L183

I think that it would affect some environments (not RGB images). Could you explain to me why you use different value for training/testing (SRL training/RL training) ?

**Comment by araffin** [comment]
> Could you explain to me why you use different value for training/testing (SRL training/RL training) ?

This was the source of a bug: when we train SRL models, we use OpenCV to load images, so BGR images.
However, during testing, we access directly images from PyBullet that are RGB.
So to be consistent, we need to convert to RGB during training.

**Comment by ncble** [comment]
I think we should definitely add your explanation to the code comment !

**Comment by ncble** [comment]
I think we should definitely add your explanation to the code comment !
